version: '3.8'
services:
  etap-db:
    image: postgres:14
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: etap
    networks:
      - database
networks:
   database: